sudo: required

services:
  - docker

 // it is a series of command that run before our test run

before_install: 
  - docker build -t frontend-web/docker-react -f Dockerfile.dev .

  script:
   - docker run -r CI=true frontend-web/docker-react npm run test 


